name: CI/CD For Testing

on:
  pull_request:
    branches:
      - main

job:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm Install && npx prisma generate

      - name: Run Test
        run: npm run test
