name: CI/CD For Testing

on:
  pull_request:
    branches:
      - main

job:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setups-node@v2
        with:
          node-verstion: 20

      - name: Install dependencies
        run: npm Install && npx prisma generate

      - name: Run Test
        run: npm run test
